services:
  nginx:
    volumes:
      - ./nginx/conf.d/upstream_green.conf:/etc/nginx/conf.d/upstream.conf
      - frontend-green-build:/usr/share/nginx/html

  frontend:
    image: kst1040/omypic-frontend:latest
    container_name: omypic-green-frontend
    env_file:
      - .env
    volumes:
      - frontend-green-build:/usr/share/nginx/html
    command: ["sh", "-c", "cp -r /app/dist/* /usr/share/nginx/html/ && echo 'Files copied to green volume' && tail -f /dev/null"]
    networks:
      - omypic-network

  backend:
    image: kst1040/omypic-backend:latest
    container_name: omypic-green-backend
    env_file:
      - .env
    expose:
      - 8001
    networks:
      - omypic-network