global:
  scrape_interval: 5s  # 5초마다 데이터를 가져옴

scrape_configs:
  - job_name: "fastapi"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["127.0.0.1:8010"]  # FastAPI 서버의 metrics 엔드포인트
